# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.create(nome: "Humberto", password: "123456", email: "humberto@gmail.com", is_admin: true)
User.create(nome: "Daniel", password: "teste123", email: "daniel@gmail.com")
User.create(nome: "David", password: "123", email: "david@gmail.com")
User.create(nome: "Athos", password: "athospnc", email: "athos@gmail.com")
User.create(nome: "Natalia", password: "serieb123", email: "natalia@gmail.com")

Preference.create(tipo: "Filmes", descricao: "Interestelar")
Preference.create(tipo: "Filmes", descricao: "Guardiões da Galáxia")
Preference.create(tipo: "Filmes", descricao: "O Grande Hotel Budapeste")
Preference.create(tipo: "Filmes", descricao: "A Origem")
Preference.create(tipo: "Filmes", descricao: "Dunkirk")
Preference.create(tipo: "Filmes", descricao: "Deadpool")
Preference.create(tipo: "Filmes", descricao: "Clube da Luta")
Preference.create(tipo: "Filmes", descricao: "O Lobo de Wallstreet")
Preference.create(tipo: "Filmes", descricao: "Blade Runner 2049")
Preference.create(tipo: "Filmes", descricao: "Django Livre")
Preference.create(tipo: "Filmes", descricao: "Logan")
Preference.create(tipo: "Filmes", descricao: "Birdman")
Preference.create(tipo: "Filmes", descricao: "Bastardos Inglórios")
Preference.create(tipo: "Filmes", descricao: "Star Wars")
Preference.create(tipo: "Filmes", descricao: "Mulher-Maravilha")
Preference.create(tipo: "Filmes", descricao: "Perdido em Marte")
Preference.create(tipo: "Filmes", descricao: "Drive")
Preference.create(tipo: "Filmes", descricao: "O Iluminado")
Preference.create(tipo: "Filmes", descricao: "O Regresso")
Preference.create(tipo: "Filmes", descricao: "The Avengers: Os Vingadores")
Preference.create(tipo: "Filmes", descricao: "O Poderoso Chefão")
Preference.create(tipo: "Filmes", descricao: "Pantera Negra")
Preference.create(tipo: "Filmes", descricao: "O Abutre")
Preference.create(tipo: "Filmes", descricao: "Os Oito Odiados")
Preference.create(tipo: "Filmes", descricao: "Alien, o Oitavo Passageiro")
Preference.create(tipo: "Filmes", descricao: "A Rede Social")
Preference.create(tipo: "Filmes", descricao: "2001: Uma Odisseia no Espaço")
Preference.create(tipo: "Filmes", descricao: "Gravidade")
Preference.create(tipo: "Filmes", descricao: "Kill Bill: Vol. 1")
Preference.create(tipo: "Filmes", descricao: "It: A Coisa")
Preference.create(tipo: "Filmes", descricao: "O Silêncio dos Inocentes")
Preference.create(tipo: "Filmes", descricao: "Zootopia - Essa Cidade é o Bicho")
Preference.create(tipo: "Filmes", descricao: "Se7en - Os Sete Crimes Capitais")
Preference.create(tipo: "Filmes", descricao: "De Volta para o Futuro")
Preference.create(tipo: "Filmes", descricao: "Kingsman: Serviço Secreto")
Preference.create(tipo: "Filmes", descricao: "Doutor Estranho")
Preference.create(tipo: "Filmes", descricao: "Onde os Fracos Não Têm Vez")
Preference.create(tipo: "Filmes", descricao: "Matrix")
Preference.create(tipo: "Filmes", descricao: "Jurassic Park: O Parque dos Dinossauros")
Preference.create(tipo: "Filmes", descricao: "Cisne Negro")
Preference.create(tipo: "Filmes", descricao: "Forrest Gump: O Contador de Histórias")
Preference.create(tipo: "Filmes", descricao: "A Viagem de Chihiro")
Preference.create(tipo: "Filmes", descricao: "Um Sonho de Liberdade")
Preference.create(tipo: "Filmes", descricao: "O Quarto de Jack")
Preference.create(tipo: "Filmes", descricao: "O Grande Lebowski")
Preference.create(tipo: "Filmes", descricao: "Amnésia")
Preference.create(tipo: "Filmes", descricao: "Cães de Aluguel")
Preference.create(tipo: "Filmes", descricao: "Scott Pilgrim Contra o Mundo")
Preference.create(tipo: "Filmes", descricao: "Laranja Mecânica")
Preference.create(tipo: "Filmes", descricao: "Os Bons Companheiros")
Preference.create(tipo: "Filmes", descricao: "Esquadrão Suicida")
Preference.create(tipo: "Filmes", descricao: "Sangue Negro")
Preference.create(tipo: "Filmes", descricao: "WALL-E")
Preference.create(tipo: "Filmes", descricao: "Donnie Darko")
Preference.create(tipo: "Filmes", descricao: "Beleza Americana")
Preference.create(tipo: "Filmes", descricao: "Viva - A Vida é uma Festa")
Preference.create(tipo: "Filmes", descricao: "Em Ritmo de Fuga")
Preference.create(tipo: "Filmes", descricao: "La La Land: Cantando Estações")
Preference.create(tipo: "Filmes", descricao: "Corra!")
Preference.create(tipo: "Filmes", descricao: "A Chegada")

Preference.create(tipo: "Livros", descricao: "Com amor, Simon")
Preference.create(tipo: "Livros", descricao: "O homem mais rico da Babilônia")
Preference.create(tipo: "Livros", descricao: "Um experimento de amor em Nova York")
Preference.create(tipo: "Livros", descricao: "Antes que o café esfrie")
Preference.create(tipo: "Livros", descricao: "Café com Deus Pai")
Preference.create(tipo: "Livros", descricao: "Verity")
Preference.create(tipo: "Livros", descricao: "A hora da estrela")
Preference.create(tipo: "Livros", descricao: "É assim que começa")
Preference.create(tipo: "Livros", descricao: "A Biblioteca da Meia-Noite")
Preference.create(tipo: "Livros", descricao: "Vermelho, branco e sangue azul")
Preference.create(tipo: "Livros", descricao: "É assim que acaba")
Preference.create(tipo: "Livros", descricao: "Gatilhos Mentais")
Preference.create(tipo: "Livros", descricao: "Amêndoas")
Preference.create(tipo: "Livros", descricao: "Um dia muito mal-humorado")
Preference.create(tipo: "Livros", descricao: "Os segredos da mente milionária")
Preference.create(tipo: "Livros", descricao: "Heartstopper")
Preference.create(tipo: "Livros", descricao: "1984")
Preference.create(tipo: "Livros", descricao: "A revolução dos bichos: Um conto de fadas")
Preference.create(tipo: "Livros", descricao: "Todas as suas (im)perfeições")
Preference.create(tipo: "Livros", descricao: "Melhor do que nos filmes")
Preference.create(tipo: "Livros", descricao: "Os miseráveis")
Preference.create(tipo: "Livros", descricao: "Tudo é rio")
Preference.create(tipo: "Livros", descricao: "Torto arado")
Preference.create(tipo: "Livros", descricao: "Cartas de um diabo a seu aprendiz")
Preference.create(tipo: "Livros", descricao: "Até o verão terminar")
Preference.create(tipo: "Livros", descricao: "Fahrenheit 451")


Preference.create(tipo: "Jogos", descricao: "Minecraft")
Preference.create(tipo: "Jogos", descricao: "Apex Legends")
Preference.create(tipo: "Jogos", descricao: "Fortnite")
Preference.create(tipo: "Jogos", descricao: "Counter-Strike: Global Offensive")
Preference.create(tipo: "Jogos", descricao: "Hearthstone: Heroes of Warcraft")
Preference.create(tipo: "Jogos", descricao: "League of Legends")
Preference.create(tipo: "Jogos", descricao: "Among Us")
Preference.create(tipo: "Jogos", descricao: "Dota 2")
Preference.create(tipo: "Jogos", descricao: "Free Fire")
Preference.create(tipo: "Jogos", descricao: "Roblox")
Preference.create(tipo: "Jogos", descricao: "Overwatch")
Preference.create(tipo: "Jogos", descricao: "Valorant")
Preference.create(tipo: "Jogos", descricao: "Rainbow Six: Siege")
Preference.create(tipo: "Jogos", descricao: "Genshin Impact")
Preference.create(tipo: "Jogos", descricao: "FIFA")
Preference.create(tipo: "Jogos", descricao: "GTA V")
Preference.create(tipo: "Jogos", descricao: "The Legend of Zelda")
Preference.create(tipo: "Jogos", descricao: "The Witcher")
Preference.create(tipo: "Jogos", descricao: "God of War")
Preference.create(tipo: "Jogos", descricao: "The Last of Us")
Preference.create(tipo: "Jogos", descricao: "Uncharted")
Preference.create(tipo: "Jogos", descricao: "Shadow of the Colossus")
Preference.create(tipo: "Jogos", descricao: "Portal")
Preference.create(tipo: "Jogos", descricao: "Resident Evil")
Preference.create(tipo: "Jogos", descricao: "Final Fantasy")
Preference.create(tipo: "Jogos", descricao: "Dark Souls")
Preference.create(tipo: "Jogos", descricao: "Forza Horizon")
Preference.create(tipo: "Jogos", descricao: "Tekken")
Preference.create(tipo: "Jogos", descricao: "Street Fighter")
Preference.create(tipo: "Jogos", descricao: "Mortal Kombat")
Preference.create(tipo: "Jogos", descricao: "Elden Ring")
Preference.create(tipo: "Jogos", descricao: "Starcraft")
Preference.create(tipo: "Jogos", descricao: "Gran Turismo")
Preference.create(tipo: "Jogos", descricao: "Undertale")
Preference.create(tipo: "Jogos", descricao: "Call of Duty")
Preference.create(tipo: "Jogos", descricao: "Battlefield")
Preference.create(tipo: "Jogos", descricao: "BioShock")
Preference.create(tipo: "Jogos", descricao: "Metal Gear")
Preference.create(tipo: "Jogos", descricao: "Pokémon")
Preference.create(tipo: "Jogos", descricao: "Super Mario")
Preference.create(tipo: "Jogos", descricao: "Tetris")
Preference.create(tipo: "Jogos", descricao: "Assassin's Creed")
Preference.create(tipo: "Jogos", descricao: "Hitman")
Preference.create(tipo: "Jogos", descricao: "The Sims")
Preference.create(tipo: "Jogos", descricao: "Sonic")
Preference.create(tipo: "Jogos", descricao: "Gears of War")
Preference.create(tipo: "Jogos", descricao: "Mass Effect")
Preference.create(tipo: "Jogos", descricao: "Halo")

Preference.create(tipo: "Músicas", descricao: "The Beatles")
Preference.create(tipo: "Músicas", descricao: "The Rolling Stones")
Preference.create(tipo: "Músicas", descricao: "Elton John")
Preference.create(tipo: "Músicas", descricao: "Mariah Carey")
Preference.create(tipo: "Músicas", descricao: "Madonna")
Preference.create(tipo: "Músicas", descricao: "Michael Jackson")
Preference.create(tipo: "Músicas", descricao: "Taylor Swift")
Preference.create(tipo: "Músicas", descricao: "Stevie Wonder")
Preference.create(tipo: "Músicas", descricao: "Elvis Presley")
Preference.create(tipo: "Músicas", descricao: "Drake")
Preference.create(tipo: "Músicas", descricao: "Prince")
Preference.create(tipo: "Músicas", descricao: "Rihanna")
Preference.create(tipo: "Músicas", descricao: "Eminem")
Preference.create(tipo: "Músicas", descricao: "Bee Gees")
Preference.create(tipo: "Músicas", descricao: "Adele")
Preference.create(tipo: "Músicas", descricao: "Beyoncé")
Preference.create(tipo: "Músicas", descricao: "Eric Clapton")
Preference.create(tipo: "Músicas", descricao: "Bruno Mars")
Preference.create(tipo: "Músicas", descricao: "Led Zeppelin")
Preference.create(tipo: "Músicas", descricao: "Maroon 5")
Preference.create(tipo: "Músicas", descricao: "Bon Jovi")
Preference.create(tipo: "Músicas", descricao: "JAY-Z")
Preference.create(tipo: "Músicas", descricao: "Nickelback")
Preference.create(tipo: "Músicas", descricao: "Justin Bieber")
Preference.create(tipo: "Músicas", descricao: "Lady Gaga")
Preference.create(tipo: "Músicas", descricao: "Britney Spears")
Preference.create(tipo: "Músicas", descricao: "Katy Perry")
Preference.create(tipo: "Músicas", descricao: "Miley Cyrus")
Preference.create(tipo: "Músicas", descricao: "Earth, Wind & Fire")
Preference.create(tipo: "Músicas", descricao: "U2")
Preference.create(tipo: "Músicas", descricao: "Aerosmith")
Preference.create(tipo: "Músicas", descricao: "The Black Eyed Peas")
Preference.create(tipo: "Músicas", descricao: "Justin Timberlake")
Preference.create(tipo: "Músicas", descricao: "Ed Sheeran")
Preference.create(tipo: "Músicas", descricao: "Pink Floyd")
Preference.create(tipo: "Músicas", descricao: "Queen")
Preference.create(tipo: "Músicas", descricao: "Kanye West")
Preference.create(tipo: "Músicas", descricao: "Guns N Roses")
Preference.create(tipo: "Músicas", descricao: "Linkin Park")
Preference.create(tipo: "Músicas", descricao: "Backstreet Boys")
Preference.create(tipo: "Músicas", descricao: "50 Cent")
Preference.create(tipo: "Músicas", descricao: "Chico Buarque")
Preference.create(tipo: "Músicas", descricao: "Tim Maia")
Preference.create(tipo: "Músicas", descricao: "Roberto Carlos")
Preference.create(tipo: "Músicas", descricao: "Tom Jobim")
Preference.create(tipo: "Músicas", descricao: "Gal Costa")
Preference.create(tipo: "Músicas", descricao: "Gilberto Gil")
Preference.create(tipo: "Músicas", descricao: "Jorge Ben Jor")
Preference.create(tipo: "Músicas", descricao: "Luiz Gonzaga")
Preference.create(tipo: "Músicas", descricao: "Rita Lee")
Preference.create(tipo: "Músicas", descricao: "Marisa Monte")
Preference.create(tipo: "Músicas", descricao: "Cazuza")
Preference.create(tipo: "Músicas", descricao: "Raul Seixas")
Preference.create(tipo: "Músicas", descricao: "Zé Ramalho")
Preference.create(tipo: "Músicas", descricao: "Djavan")
Preference.create(tipo: "Músicas", descricao: "Zeca Pagodinho")
Preference.create(tipo: "Músicas", descricao: "Alceu Valença")
Preference.create(tipo: "Músicas", descricao: "Cássia Eller")
Preference.create(tipo: "Músicas", descricao: "Anitta")
Preference.create(tipo: "Músicas", descricao: "Alok")
Preference.create(tipo: "Músicas", descricao: "Luan Santana")
Preference.create(tipo: "Músicas", descricao: "Gusttavo Lima")
Preference.create(tipo: "Músicas", descricao: "Michel Teló")
Preference.create(tipo: "Músicas", descricao: "Ivete Sangalo")
Preference.create(tipo: "Músicas", descricao: "Xuxa")
Preference.create(tipo: "Músicas", descricao: "Legião Urbana")
Preference.create(tipo: "Músicas", descricao: "Os Mutantes")
Preference.create(tipo: "Músicas", descricao: "Titãs")
Preference.create(tipo: "Músicas", descricao: "Os Paralamas do Sucesso")
Preference.create(tipo: "Músicas", descricao: "Sepultura")
Preference.create(tipo: "Músicas", descricao: "Charlie Brown Jr.")
Preference.create(tipo: "Músicas", descricao: "Barão Vermelho")
Preference.create(tipo: "Músicas", descricao: "Capital Inicial")
Preference.create(tipo: "Músicas", descricao: "Kid Abelha")
Preference.create(tipo: "Músicas", descricao: "Skank")
Preference.create(tipo: "Músicas", descricao: "Engenheiros do Hawaii")
Preference.create(tipo: "Músicas", descricao: "Los Hermanos")
Preference.create(tipo: "Músicas", descricao: "NX Zero")
Preference.create(tipo: "Músicas", descricao: "Secos & Molhados")
Preference.create(tipo: "Músicas", descricao: "Mamonas Assassinas")
Preference.create(tipo: "Músicas", descricao: "Raimundos")
Preference.create(tipo: "Músicas", descricao: "Roupa Nova")
Preference.create(tipo: "Músicas", descricao: "Dead Fish")
Preference.create(tipo: "Músicas", descricao: "Racionais MC's")
Preference.create(tipo: "Músicas", descricao: "Jota Quest")
Preference.create(tipo: "Músicas", descricao: "Tribalistas")
Preference.create(tipo: "Músicas", descricao: "Coldplay")
Preference.create(tipo: "Músicas", descricao: "The Weeknd")
Preference.create(tipo: "Músicas", descricao: "Lana Del Rey")
Preference.create(tipo: "Músicas", descricao: "Imagine Dragons")
Preference.create(tipo: "Músicas", descricao: "Shakira")
Preference.create(tipo: "Músicas", descricao: "Harry Styles")
Preference.create(tipo: "Músicas", descricao: "Sia")
Preference.create(tipo: "Músicas", descricao: "Billie Eilish")
Preference.create(tipo: "Músicas", descricao: "Bob Marley")
Preference.create(tipo: "Músicas", descricao: "Metallica")
Preference.create(tipo: "Músicas", descricao: "Red Hot Chili Peppers")
Preference.create(tipo: "Músicas", descricao: "Scorpions")
Preference.create(tipo: "Músicas", descricao: "Olivia Rodrigo")
Preference.create(tipo: "Músicas", descricao: "Foo Fighters")
Preference.create(tipo: "Músicas", descricao: "Ludmilla")
Preference.create(tipo: "Músicas", descricao: "Ariana Grande")
Preference.create(tipo: "Músicas", descricao: "Evanescence")
Preference.create(tipo: "Músicas", descricao: "Arctic Monkeys")
Preference.create(tipo: "Músicas", descricao: "AC/DC")
Preference.create(tipo: "Músicas", descricao: "Frank Sinatra")
Preference.create(tipo: "Músicas", descricao: "Oasis")
Preference.create(tipo: "Músicas", descricao: "Nirvana")
Preference.create(tipo: "Músicas", descricao: "Post Malone")
Preference.create(tipo: "Músicas", descricao: "Dua Lipa")
Preference.create(tipo: "Músicas", descricao: "BTS")
Preference.create(tipo: "Músicas", descricao: "System of a Down")
Preference.create(tipo: "Músicas", descricao: "Shawn Mendes")

Preference.create(tipo: "Programas de TV", descricao: "Breaking Bad")
Preference.create(tipo: "Programas de TV", descricao: "Game of Thrones")
Preference.create(tipo: "Programas de TV", descricao: "Família Soprano")
Preference.create(tipo: "Programas de TV", descricao: "Chernobyl")
Preference.create(tipo: "Programas de TV", descricao: "Sherlock")
Preference.create(tipo: "Programas de TV", descricao: "Friends")
Preference.create(tipo: "Programas de TV", descricao: "The Office")
Preference.create(tipo: "Programas de TV", descricao: "Os Simpsons")
Preference.create(tipo: "Programas de TV", descricao: "Narcos")
Preference.create(tipo: "Programas de TV", descricao: "Stranger Things")
Preference.create(tipo: "Programas de TV", descricao: "Black Mirror")
Preference.create(tipo: "Programas de TV", descricao: "Seinfeld")
Preference.create(tipo: "Programas de TV", descricao: "Sex and the City")
Preference.create(tipo: "Programas de TV", descricao: "Peaky Blinders")
Preference.create(tipo: "Programas de TV", descricao: "I Love Lucy")
Preference.create(tipo: "Programas de TV", descricao: "Supernatural")
Preference.create(tipo: "Programas de TV", descricao: "House of Cards")
Preference.create(tipo: "Programas de TV", descricao: "The Boys")
Preference.create(tipo: "Programas de TV", descricao: "Fleabag")
Preference.create(tipo: "Programas de TV", descricao: "Dr. House")
Preference.create(tipo: "Programas de TV", descricao: "Dexter")
Preference.create(tipo: "Programas de TV", descricao: "Sons of Anarchy")
Preference.create(tipo: "Programas de TV", descricao: "Sex Education")
Preference.create(tipo: "Programas de TV", descricao: "The Sandman")
Preference.create(tipo: "Programas de TV", descricao: "Wandinha")
Preference.create(tipo: "Programas de TV", descricao: "The Good Place")
Preference.create(tipo: "Programas de TV", descricao: "Anne With an E")
Preference.create(tipo: "Programas de TV", descricao: "Bridgerton")
Preference.create(tipo: "Programas de TV", descricao: "The Walking Dead")
Preference.create(tipo: "Programas de TV", descricao: "3%")
Preference.create(tipo: "Programas de TV", descricao: "Suits")
Preference.create(tipo: "Programas de TV", descricao: "Orange Is The New Black")
Preference.create(tipo: "Programas de TV", descricao: "O Mundo Sombrio de Sabrina")
Preference.create(tipo: "Programas de TV", descricao: "A Maldição da Residência Hill")
Preference.create(tipo: "Programas de TV", descricao: "La Casa de papel")
Preference.create(tipo: "Programas de TV", descricao: "Brooklyn Nine-Nine")
Preference.create(tipo: "Programas de TV", descricao: "Dark")
Preference.create(tipo: "Programas de TV", descricao: "The Crown")
Preference.create(tipo: "Programas de TV", descricao: "Teen Wolf")
Preference.create(tipo: "Programas de TV", descricao: "Lucifer")
Preference.create(tipo: "Programas de TV", descricao: "Round 6")
Preference.create(tipo: "Programas de TV", descricao: "Elite")
Preference.create(tipo: "Programas de TV", descricao: "WandaVision")
Preference.create(tipo: "Programas de TV", descricao: "You")
Preference.create(tipo: "Programas de TV", descricao: "The Handmaid's Tale")
Preference.create(tipo: "Programas de TV", descricao: "Loki")
Preference.create(tipo: "Programas de TV", descricao: "Grey's Anatomy")
Preference.create(tipo: "Programas de TV", descricao: "O Gambito da Rainha")


# User.create(id: 1, nome: 'joe', senha: 'biden')
# User.create(id: 2, nome: 'barack', senha: 'obama')
# Preference.create(id: 1, tipo: 'a', descricao: 'a')
# Preference.create(id: 2, tipo: 'b', descricao: 'b')
ListPreference.create(id: 1, user_id: 1, preference_id: 1)
ListPreference.create(id: 2, user_id: 1, preference_id: 2)
# Group.create(id: 1, nome: 'a', tipo: 'a', descricao: 'teste', preference_id: 1)
# Group.create(id: 2, nome: 'b', tipo: 'b', descricao: 'teste', preference_id: 2)
# ListGroupUser.create(user_id: 1, group_id: 1)
# ListGroupUser.create(user_id: 2, group_id: 1)
# ListGroupUser.create(user_id: 1, group_id: 2)
# ListGroupUser.create(user_id: 2, group_id: 2)
# Chat.create(id: 1, id_match: nil, id_group: 1)
# Message.create(id: 1, chat_id: 1, user_id: 1, conteudo: 'kys')
# Message.create(id: 2, chat_id: 1, user_id: 1, conteudo: 'sorry')
# Match.create(user_id: 1, user_id2: 2, match_grade: 'a')
